config/routes.rb
Turbi::Application.routes.draw do

  get "users/show"

  resources :projects, except: [:destroy] do
    resources :supports, only: [:new, :create] do
      member do
        get "success_callback"
        get "cancel_callback"
      end
    end
  end

  root to: "projects#index"

  resources :authorizations, only: [:destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show]

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :supports
  attr_accessible :headline, :code_funded, :description, :expires_at, :goal, :name, :repository, :video, :visible, :user_id

  # Validates
  validates :name, :headline, :description, :goal, :video, :user, :presence => true
  validates :repository, :video, format: {with: URI::regexp(%w[http https]), allow_nil: true, allow_blank: true}
  before_create :store_image_url

  validates_each :expires_at do |record, attr, value|
    record.errors.add(attr,
      I18n.t("activerecord.errors.models.project.attributes.expires_at")
    ) if value && value < 1.week.from_now
  end

  validates_length_of :headline, :maximum => 140

  has_vimeo_video :video, :message => I18n.t('activerecord.errors.models.project.attributes.vimeo_regex_validation')

  # Scopes
  scope :visible, where(visible: true).order("created_at DESC")
  scope :expired, where("expires_at < current_timestamp").order("expires_at DESC")
  scope :active, lambda { visible - expired }

  auto_html_for :description do
    html_escape
    image
    youtube :width => 460, :height => 262
    vimeo :width => 460, :height => 262
    redcarpet
    link :target => "_blank"
  end

  def cannot_edit?(attr)
    (attr.to_sym != :code_funded) && persisted?
  end

  def visible?
    visible
  end

  def amount_reached
    supports.confirmed.sum(&:amount)
  end

  def active?
    visible? and not expired?
  end

  def expired?
    expires_at < Time.now
  end

  def successful?
    amount_reached >= goal
  end

  def days_left
    days = (expires_at.to_date - Date.today).to_i
    days > 0 ? days : 0
  end

  def percent
    ((amount_reached / goal * 100).abs).round.to_i
  end

  def progress
    return 100 if percent > 100
    percent
  end

  protected
  def store_image_url
    self.image = vimeo.thumbnail unless self.image
  end
end

app/controllers/projects_controller.rb
class ProjectsController < InheritedResources::Base
  actions :all, except: [:destroy]
  load_and_authorize_resource only: [:edit, :update]

  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :assign_user_id, only: [:create]

  def index
    @active_projects = Project.active
    @expired_projects = Project.expired
    index!
  end

  def create
    create! do |success, failure|
      success.html do
        redirect_to project_path(@project), notice: t("projects.create.needs_approval")
      end
    end
  end

  def show
    @project = Project.find(params[:id])
    if @project.visible?
      show!
    elsif @project.user == current_user
      flash[:notice] = t('projects.show.user_project_needs_approval')
      show!
    else
      redirect_to root_path, notice: t("projects.show.needs_approval")
    end
  end

  def update
    unless params[:project].nil?
      params[:project].reject! { |attr| @project.cannot_edit?(attr) }
    end
    update!
  end

  protected
  def assign_user_id
    params[:project][:user_id] = current_user.id if params[:project]
  end
end

app/views/projects/_box.html.slim
.show class="box#{" centered" if i % 3 == 1}" style="#{"clear: left" if i % 3 == 0}"
  div
    = link_to project_path(project) do
      .img-overflow
        = image_tag project.image, alt: project.name
      h2.project-title = truncate project.name.upcase, length: 140
      p.user_name = project.user.name.split(" ").first.titleize
      p.description
        = project.headline
      .bottom-content
        .progress-text
          span
            strong
              = project.days_left
              |  #{t('days')}
            | #{t('remaining').upcase}
          span
            strong
              = project.percent
              | %
            | #{t('reached').upcase}
        .progress.progress-success.progress-striped
          .bar style="width: #{project.progress}%"

app/views/projects/_comments.html.slim
.comments
  .fb-comments data-href="#{request.url.html_safe}" data-num-posts="10" data-width="940"

app/views/projects/_form.html.slim
= simple_form_for(@project) do |f|
  .form-inputs.modal-body
    = f.input :name, required: true, autofocus: true, input_html: {class: "span12"}, readonly: @project.cannot_edit?(:name)
    = f.input :description, required: true, input_html: {class: "span12"}, readonly: @project.cannot_edit?(:description)
    = f.input :expires_at, required: true, input_html: {style: "width: auto"}, start_year: Date.today.year, start_day: Date.today.day, readonly: @project.cannot_edit?(:expires_at), :disabled => @project.cannot_edit?(:expires_at)
    = f.input :headline, required: true, input_html: {class: "span12", maxlength: "140"}, readonly: @project.cannot_edit?(:headline)
    = f.input :video, required: true, input_html: {class: "span12"}, readonly: @project.cannot_edit?(:video)
    = f.input :repository, required: true, as: :url, input_html: {class: "span12"}, readonly: @project.cannot_edit?(:repository)
    - if @project.persisted?
      = f.input :code_funded, as: :url, input_html: {class: "span12"}, readonly: @project.cannot_edit?(:code_funded)
    = f.input :goal, required: true, input_html: {class: "span12", min: 10, :"data-input-type" => "number",  :"data-input-number-min" => "10"}, readonly: @project.cannot_edit?(:goal)

  = f.button :submit, t("project.submit.create"), class: "btn btn-large", style: "width: 935px"

app/views/projects/_share_social.html.slim
.share-social
  .fb-like data-href="#{request.url.html_safe}" data-send="false" data-layout="button_count" data-width="140" data-show-faces="false" style="vertical-align:top;min-width:100px"
  = link_to "Tweet", "https://twitter.com/share", class: "twitter-share-button", :"data-url" => "#{request.url.html_safe}", :"data-text" => "Texto que vai ser usado", :"data-via" => "turbime", :"data-lang" => "pt", :"data-count" => "horizontal"
  .g-plusone data-size="medium" data-href="#{request.url.html_safe}"

app/views/projects/edit.html.slim
- content_for(:title) do
  = t('projects.edit.title')
section.edit_project
  .center
    h1.page-title = t('.title')
    = render "form"

app/views/projects/index.html.slim
- content_for(:title) do
  = t('projects.title')
section.home-intro
  .center
    .pull-left
      h1 = t('home.intro.title')
      p = t('home.intro.pitch')
      = link_to t('home.start_your_project'), new_project_path, class: "btn"
    .pull-right
      iframe src="http://player.vimeo.com/video/10092822?title=0&amp;byline=0&amp;portrait=0&amp;color=ffffff" width="500" height="281" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen>
    .clear

section.box-list
  .center
    h2.page-title = t('.active_projects')
    - @active_projects.each_with_index do |project,i|
      = render 'projects/box', {project: project, i: i}
    .clear

- if @expired_projects.size > 0
  section.box-list
    .center
      h2.page-title = t('.expired_projects')
      - @expired_projects.each_with_index do |project,i|
        = render 'projects/box', {project: project, i: i}
      .clear

section.steps
  .center
    #home_steps
      h2.title = t('home.how_works')
      ul
        li.span3
          span.title.span1.step1
          span.span1 = t('home.steps.one')
        li.span3
          span.title.span1.step2
          span.span1 = t('home.steps.two')
        li.span3
          span.title.span1.step3
          span.span1 = t('home.steps.three')
      .clear

app/views/projects/new.html.slim
- content_for(:title) do
  = t('.new_project')
.center.new_project

  h1.page-title = t(".new_project")

  ul#steps
    li
      strong Create your project.
      |  Can be related to development of any software feature.
    li
      strong People support the development with money.
      |  You can know if they really want the feature.
    li
      strong Development happens and you share its link.
      |  You can be a developer or entrepreneur paying others to code. Code written, you edit this project and add the link for the feature.
  = render "form"

app/views/projects/show.html.slim
- content_for(:title) do
  = @project.name
section
  .center
    h1.page-title
      = @project.name
      - if user_signed_in? && @project.user == current_user
        = link_to t('.edit'), edit_project_path(@project), class: 'pull-right'
    .clear
    p
      = t('project_by')
      = link_to @project.user.name, user_path(@project.user)
    .user-info.project
      .pull-left.video
        iframe src="#{@project.vimeo.embed_url.html_safe}?title=0&amp;byline=0&amp;portrait=0&amp" width="640" height="430" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen
      .pull-left.about
        p
          span.big
            = @project.supports.confirmed.count
          = t('.backers')
        p
          span.big.block = number_to_currency(@project.amount_reached)
          span.block
          = t('.pledged_of', total: number_to_currency(@project.goal))
        p
          span.big.block
            = @project.days_left
          span.block
            = t('days_to_go')
        .donate-button[class="#{'not_successful' if not @project.successful? and @project.expired?} #{'successful' if @project.successful? and @project.expired?}"]
          .hide-ended#pledge-wrap
            = link_to "#{@project.active? ? new_project_support_url(@project) : '#'}", class: "button roundsmall", id: "button-back-this-proj", title: t('.new_support_title'), id: "donate" do
              - if not @project.successful? and @project.expired?
                = t('project.not_funded')
              - elsif @project.successful? and @project.expired?
                = t('project.funded')
              - else
                = t('.new_support')
                small= t('.new_support_hint')
      .clear
    = render 'share_social'

    - if @project.repository.present? || @project.code_funded.present?
      .project-links
        - if @project.code_funded.present?
          .project-code_funded.span5.btn
            = link_to @project.code_funded.gsub(/http(s)?:\/\//, ''), @project.code_funded
        - if @project.repository.present?
          .project-repository[class="#{@project.code_funded? ? 'span5 offset1' : 'span9 offset0'}"]
            = image_tag "web-github.png"
            = link_to @project.repository.gsub(/http(s)?:\/\//, ''), @project.repository

    .project-description
      = @project.description_html.html_safe
    
    h1.comments-title = t('.comments')
    = render 'comments'