config/routes.rb
Turbi::Application.routes.draw do

  get "users/show"

  resources :projects, except: [:destroy] do
    resources :supports, only: [:new, :create] do
      member do
        get "success_callback"
        get "cancel_callback"
      end
    end
  end

  root to: "projects#index"

  resources :authorizations, only: [:destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users, only: [:show]

end

app/models/support.rb
class Support < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :amount, :payment_method, :payment_token, :transaction_id, :terms
  validates :user, :project, :amount, :payment_token, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 5.00 }
  validates :terms, acceptance: {:accept => "1"}, allow_nil: false, if: lambda { |s| s.new_record? }
  attr_protected :confirmed
  before_validation :create_payment_token, only: [:create], if: lambda { |s| s.new_record? }

  # Scopes
  scope :confirmed, where(confirmed: true)

  def confirm!
    update_column :confirmed, true
  end

  protected
  def create_payment_token
    self.payment_token = Digest::MD5.hexdigest "#{SecureRandom.hex(5)}-#{DateTime.now.to_s}"
  end
end

app/controllers/supports_controller.rb
class SupportsController < InheritedResources::Base
  before_filter :authenticate_user!
  before_filter :assign_user_id_and_project_id, only: [:create]
  actions :new, :create
  before_filter do
    @project = Project.find(params[:project_id])
  end
  before_filter :access, only: [:new, :create]

  def create
    @support = Support.new params[:support]
    if @support.save
      payment = Payment.new @support.amount
      payment.setup!(
        success_callback_project_support_url(@support.project.id, @support.id),
        cancel_callback_project_support_url(@support.project.id, @support.id)
      )
      @support.update_attributes(payment_token: payment.token)

      redirect_to payment.redirect_uri
    else
      render 'new'
    end
  end

  def success_callback
    support = Support.find_by_payment_token(params[:token])
    if support
      payment = Payment.new
      payment.token = params[:token]
      payment.payer_id = params[:PayerID]
      payment.amount = support.amount
      payment.complete!

      support.confirm!
      support.update_attributes(transaction_id: payment.identifier)
      redirect_to root_url, notice: t(".supports.success_callback.successful_payment")
    else
      render nothing: true, status: :unprocessable_entity
    end
  end

  def cancel_callback
    redirect_to root_url, notice: t(".supports.success_callback.canceled_payment")
  end

  protected
  def access
    raise CanCan::AccessDenied unless @project.active?
  end
  def assign_user_id_and_project_id
    params[:support][:user_id] = current_user.id if params[:support]
    params[:support][:project_id] = params[:project_id]
  end
end

app/views/supports/new.html.slim
section.new_support
  .center
    h1.page-title
      | Backing: 
      a = link_to @project.name, project_path(@project)
    .project
      .image.pull-left
        = image_tag @project.image
      .headline.pull-left
        = simple_format @project.headline
      .clear


    = simple_form_for @support, url: project_supports_path(params[:project_id]) do |f|
        .model-body.form-inputs
          = f.input :amount, pattern: "\d+[\.\d+]?", title: t('only_numbers')
          = text_area_tag :terms_text, File.read("#{Rails.root}/app/views/supports/terms.#{I18n.locale}.txt")
          = f.input :terms, as: :boolean, label: "I accept the terms"
          = f.button :submit, class: "btn btn-large", value: "Pay now"
          .paypal_image.pull-right
            = image_tag('paypal.jpg')
          .clear